### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by ninevra** [ninevra/Simple-Temporary-Containers#17]
We've got new features, should release when practical & the new API is finalized.

**Comment by maximbaz** [comment]
TODO for me to delete [a duplicate extension](https://addons.mozilla.org/en-US/firefox/addon/simple-temporary-containers-2/) after the release.

I had to publish it because there is no other practical way to use a locally modified extension, and to be honest I didn't expect a reply after #15 stood for a while without response :upside_down_face:, I just wanted to solve my long lasting pain point :grin:  Glad you did merge the PR and continued to improve upon it! :heart:

**Comment by ninevra** [comment]
It's out! Changed the special name to `%NEW_TEMP_CONTAINER%`. i tested as much as i reasonably could; let me know if it doesn't work for you.

**Comment by maximbaz** [comment]
It's perfect! Many thanks for all your help! I have deleted the duplicate extension :+1:
