### ISSUE TITLE
Request: Integrate in Multi Account Containers context menu

### ISSUE THREAD

**Issue by laundmo** [ninevra/Simple-Temporary-Containers#3]
when right clicking a link with the Multi Account Containers installed theres a "open link in new container tab" option.
i would love to see this extensions temporary tab option in that ment

**Comment by ninevra** [comment]
I agree that would be cool, but I don't know of any way of accomplishing it unfortunately.

Simple Temporary Containers does provide another menu item that allows opening links in new temporary containers ("Open Link in New Temp Container Tab").

The "Open Link in New Container Tab" menu item is actually a built-in Firefox thing, not part of Multi Account Containers. I don't know of any way of hooking into it.

![stc-menus](https://user-images.githubusercontent.com/7622339/109080210-05005c80-76b5-11eb-905b-91032d28180d.png)

**Comment by laundmo** [comment]
You could look into how Facebook containers hooks into it, that repo is
available here https://github.com/mozilla/contain-facebook

**Comment by ninevra** [comment]
Yeah, I could do that, but there would be some issues:

1. Afaict, the list of containers is sorted by creation time, oldest at the top. Idk how many containers most people use, but I usually have at least a hundred, making anything beyond the oldest few tedious to find. Recreating the "new temp container" container would move it to the bottom each time, and unless it was also recreated whenever any other container was created, it would drift up in between uses.
    - In theory, to keep it at the top, we could _not_ recreate the "new temp container" container, just intercept requests made in it and move those tabs to a different container, but that would complicate the security model a lot, in ways I don't fully understand and couldn't maintain. It might also require more permissions, which is a no-go.
    - Even if we solved this problem, we'd be relying on behavior that Firefox doesn't document and could change at any time.
2. It would be a little misleading to the user, since the "new temp container" container would literally be a container, despite functioning as a button. We'd have to think about what should happen if the user edits or deletes it, and maybe how to make it function in other lists of containers, such as the about:preferences#containers list or the Multi-Account Containers browser action popup list.
3. We'd have to delete it on uninstall, which is possible to do but not possible to guarantee.

Overall I think sticking with the simple-but-imperfect approach of having a separate, custom extension menu item is probably correct. It's inconvenient, particularly because Firefox's decision-making about what qualifies as a "link context" is occasionally inconsistent, but there's value in keeping the design language consistent with other extensions and minimizing the amount of "magic" behavior.

**Comment by ninevra** [comment]
I'm closing this issue for now, since I don't see a practical way to implement this, but please do continue the discussion if you have anything else to add! Thanks for the feedback.
